import postgres from 'postgres';

const sql = postgres(process.env.POSTGRES_URL!, { ssl: 'require' });

const mappings = [
  {
    course_id: 'Build. Enthusiasts',
    lms_course_name: 'Building Enthusiasts (SR150)',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '520',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: null,
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Minecraft',
    lms_course_name: 'Minecraft',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '273',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: null,
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Mov. Models Camp',
    lms_course_name: 'Mov. Models Camp',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '520',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: null,
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Processing',
    lms_course_name: 'Processing',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '704',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '736',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Python for AI Bootcamp',
    lms_course_name: 'Python for AI Bootcamp',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '2576',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '2597',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: '262',
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Rob Eng I',
    lms_course_name: 'Rob Eng I',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '712',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '720',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: '728',
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Rob Eng II',
    lms_course_name: 'Robotics Engineer II (R600)',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '1597',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '1685',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: '1742',
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: ['1656'],
  },
  {
    course_id: 'Roblox',
    lms_course_name: 'Roblox',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '1612',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: null,
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Robot Techs',
    lms_course_name: 'Robot Techs',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '1255',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: null,
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Scratch',
    lms_course_name: 'Scratch',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '250',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '251',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: '252',
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Unity',
    lms_course_name: 'Unity',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '410',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '411',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: null,
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
  {
    course_id: 'Web Dev',
    lms_course_name: 'Web Dev',
    lms_course_link: null,
    notes: null,
    canvas_course_family: null,
    canvas_beginner_course_id: '256',
    canvas_beginner_course_name: null,
    canvas_intermediate_course_id: '1246',
    canvas_intermediate_course_name: null,
    canvas_advanced_course_id: '1261',
    canvas_advanced_course_name: null,
    canvas_additional_course_ids: [],
  },
];

async function mappingSnapshot() {
  return sql<{ course_id: string; lms_course_name: string; canvas_beginner_course_id: string | null }[]>`
    SELECT course_id, lms_course_name, canvas_beginner_course_id
    FROM camp_lms_course_mappings
    ORDER BY course_id
  `;
}

export async function POST() {
  const before = await mappingSnapshot();

  for (const mapping of mappings) {
    await sql`
      INSERT INTO camp_lms_course_mappings (
        course_id,
        lms_course_name,
        lms_course_link,
        notes,
        canvas_course_family,
        canvas_beginner_course_id,
        canvas_beginner_course_name,
        canvas_intermediate_course_id,
        canvas_intermediate_course_name,
        canvas_advanced_course_id,
        canvas_advanced_course_name,
        canvas_additional_course_ids,
        updated_at
      ) VALUES (
        ${mapping.course_id},
        ${mapping.lms_course_name},
        ${mapping.lms_course_link},
        ${mapping.notes},
        ${mapping.canvas_course_family},
        ${mapping.canvas_beginner_course_id},
        ${mapping.canvas_beginner_course_name},
        ${mapping.canvas_intermediate_course_id},
        ${mapping.canvas_intermediate_course_name},
        ${mapping.canvas_advanced_course_id},
        ${mapping.canvas_advanced_course_name},
        ${JSON.stringify(mapping.canvas_additional_course_ids)}::jsonb,
        NOW()
      )
      ON CONFLICT (course_id) DO UPDATE
      SET lms_course_name = EXCLUDED.lms_course_name,
          lms_course_link = EXCLUDED.lms_course_link,
          notes = EXCLUDED.notes,
          canvas_course_family = EXCLUDED.canvas_course_family,
          canvas_beginner_course_id = EXCLUDED.canvas_beginner_course_id,
          canvas_beginner_course_name = EXCLUDED.canvas_beginner_course_name,
          canvas_intermediate_course_id = EXCLUDED.canvas_intermediate_course_id,
          canvas_intermediate_course_name = EXCLUDED.canvas_intermediate_course_name,
          canvas_advanced_course_id = EXCLUDED.canvas_advanced_course_id,
          canvas_advanced_course_name = EXCLUDED.canvas_advanced_course_name,
          canvas_additional_course_ids = EXCLUDED.canvas_additional_course_ids,
          updated_at = NOW();
    `;
  }

  const after = await mappingSnapshot();

  return Response.json({
    ok: true,
    source: 'dev',
    upserted: mappings.length,
    beforeCount: before.length,
    afterCount: after.length,
    afterCourseIds: after.map((row) => row.course_id),
  });
}
